# Generated by Django 3.1.2 on 2020-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20201121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_sup',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='categories',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='pickup',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
