# Generated by Django 3.1.2 on 2020-10-17 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_sup',
            fields=[
                ('sup_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('numb', models.CharField(max_length=13, unique=True)),
                ('pswd', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.CharField(max_length=5)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.CharField(default='No', max_length=3)),
                ('verifyby', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('na', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sup_verify',
            fields=[
                ('address', models.FileField(upload_to='media/')),
                ('bank_d', models.FileField(upload_to='media/')),
                ('gst', models.CharField(max_length=30, unique=True)),
                ('pan', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.new_sup')),
            ],
        ),
        migrations.CreateModel(
            name='S_prod',
            fields=[
                ('prod_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_img', models.CharField(blank=True, max_length=10000, null=True)),
                ('prod_1img', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub_c', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('hsn', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory', models.IntegerField(default=0)),
                ('prod_l', models.IntegerField(default=0)),
                ('prod_w', models.IntegerField(default=0)),
                ('prod_h', models.IntegerField(default=0)),
                ('box_l', models.IntegerField(default=0)),
                ('box_w', models.IntegerField(default=0)),
                ('box_h', models.IntegerField(default=0)),
                ('s_weight', models.IntegerField(default=0)),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('marked', models.IntegerField(default=0)),
                ('listed', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
                ('disbursement', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.new_sup')),
            ],
        ),
    ]
