# Generated by Django 3.1.2 on 2020-10-29 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20201028_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('ifsc', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('status', models.CharField(default='No', max_length=5)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.new_sup')),
            ],
        ),
        migrations.CreateModel(
            name='Entity_verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.CharField(max_length=30)),
                ('bank_pan', models.CharField(max_length=30, unique=True)),
                ('e_kyc', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(default='No', max_length=30)),
                ('e_doc', models.FileField(upload_to='media/')),
                ('corporate', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.new_sup')),
            ],
        ),
        migrations.CreateModel(
            name='Representative_verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=50, unique=True)),
                ('r_name', models.CharField(max_length=30)),
                ('r_dob', models.CharField(max_length=10)),
                ('r_address', models.CharField(max_length=30)),
                ('r_kyc', models.CharField(max_length=30)),
                ('status', models.CharField(default='No', max_length=30)),
                ('r_doc', models.FileField(upload_to='media/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sup_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.new_sup')),
            ],
        ),
        migrations.DeleteModel(
            name='Sup_verify',
        ),
    ]
