# Generated by Django 3.1.2 on 2020-11-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_auto_20201120_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_prod',
            old_name='size',
            new_name='sizes',
        ),
    ]
