# Generated by Django 3.1.2 on 2020-11-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0015_auto_20201120_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_prod',
            old_name='sizes',
            new_name='size',
        ),
    ]
