# Generated by Django 3.1.2 on 2021-01-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_auto_20210104_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity_verify',
            name='gst',
        ),
        migrations.AddField(
            model_name='new_sup',
            name='gst',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='discussid',
            field=models.IntegerField(default=1),
        ),
    ]
