# Generated by Django 3.0.8 on 2021-02-23 21:56

import account.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='RepresentativeDOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='RepresentativeDoc',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\renewedcart.com\\sevensq\\seventhsq\\KYCDoc'), upload_to=account.models.get_file_path_company_repr_doc),
        ),
        migrations.AlterField(
            model_name='account',
            name='RepresentativeDocType',
            field=models.CharField(blank=True, choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN'), ('Passport', 'Passport')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='companyCategory',
            field=models.CharField(blank=True, choices=[('Interior Items', 'Interior Items')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='companyKYCDOC',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\renewedcart.com\\sevensq\\seventhsq\\KYCDoc'), upload_to=account.models.get_file_path_company_doc),
        ),
        migrations.AlterField(
            model_name='account',
            name='companyKYCDocType',
            field=models.CharField(blank=True, choices=[('Certificate Of Incorporation', 'Certificate Of Incorporation'), ('GST Registration Certificate', 'GST Registration Certificate'), ('IT Return', 'IT Return'), ('Registration Certificate', 'Registration Certificate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='companyPAN',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='compnayCIN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobileNumber',
            field=models.TextField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid mobile number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
