# Generated by Django 3.0.8 on 2021-02-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210224_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='compnayCIN',
            new_name='companyCIN',
        ),
    ]
