# Generated by Django 3.0.8 on 2021-02-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210224_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='companyCategory',
            field=models.CharField(blank=True, choices=[('Interior Items', 'Interior Items'), ('Construction', 'Construction')], max_length=20, null=True),
        ),
    ]
