# Generated by Django 3.1.2 on 2021-03-26 07:09

import account.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210302_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='RepresentativeDoc',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\pkpri\\Downloads\\Compressed\\seventhsq-master_2\\seventhsq-master\\KYCDoc'), upload_to=account.models.get_file_path_company_repr_doc),
        ),
        migrations.AlterField(
            model_name='account',
            name='companyKYCDOC',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\pkpri\\Downloads\\Compressed\\seventhsq-master_2\\seventhsq-master\\KYCDoc'), upload_to=account.models.get_file_path_company_doc),
        ),
    ]
