# Generated by Django 3.0.8 on 2021-02-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20210226_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='accontNumber',
            new_name='accountNumber',
        ),
    ]
