# Generated by Django 3.1.2 on 2020-10-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20201021_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sup',
            name='comm',
            field=models.IntegerField(default=5),
        ),
    ]
