# Generated by Django 3.1.2 on 2020-11-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_auto_20201120_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sup',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='s_prod',
            name='about',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
