# Generated by Django 3.0.8 on 2021-01-08 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('dis_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('last', models.CharField(max_length=100)),
                ('cmnt', models.IntegerField(default=0)),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Discussion')),
            ],
        ),
    ]
