# Generated by Django 3.1.2 on 2020-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_auto_20201029_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_prod',
            name='prod_status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
