# Generated by Django 3.1.2 on 2020-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20201029_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='l1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notify',
            name='l2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notify',
            name='l3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
