# Generated by Django 3.1.2 on 2020-10-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20201030_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sup',
            name='email_verified',
            field=models.CharField(default='No', max_length=4),
        ),
        migrations.AlterField(
            model_name='representative_verify',
            name='r_dob',
            field=models.IntegerField(default=0),
        ),
    ]
