# Generated by Django 3.1.2 on 2020-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_products_productimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sup',
            name='pickup',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='categories',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
