# Generated by Django 3.1.2 on 2020-11-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_auto_20201118_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_prod',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='new_sup',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='s_prod',
            name='colour',
            field=models.CharField(default='', max_length=100),
        ),
    ]
