# Generated by Django 3.1.2 on 2020-11-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_auto_20201119_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_prod',
            name='box_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='s_prod',
            name='box_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='s_prod',
            name='box_w',
            field=models.IntegerField(default=0),
        ),
    ]
