# Generated by Django 3.1.2 on 2021-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_auto_20201125_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sup',
            name='clogo',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity_verify',
            name='e_kyc',
            field=models.CharField(max_length=20),
        ),
    ]
