# Generated by Django 3.0.8 on 2021-03-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210224_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('REPRESENTATIVE', 'Representative'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
